### ISSUE TITLE
Wrong Login credentials error

### ISSUE THREAD

**Issue by 1uismar33r0** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#95] opened 2024-02-29 00:07 UTC
Fix the error where if the username entered in the login box is not the same as in the database it will throw an undefined error.

**Comment by evnd04** [comment] 2024-03-02 21:21
Is this not how its supposed to work? Or does moving it to the DB change it in some way?

**Comment by Javi510348** [comment] 2024-03-03 00:21
@evnd04 The problem is that is not showing the error message, is throwing a page not found

**Comment by evnd04** [comment] 2024-03-03 00:28
Ohh now i get it, approved.

**Closed** 2024-03-05 03:20 UTC
Labels: bug, approved, m2 human interfaces
